# Generated by Django 5.0.6 on 2024-07-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_entry_number_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('운동', '운동'), ('식단', '식단'), ('공부', '공부'), ('취미', '취미'), ('자기계발', '자기계발')], default='운동', max_length=100),
        ),
    ]
